### ISSUE TITLE
Automatic upgrade of clean_session on errors has unwanted side effects

### ISSUE THREAD

**Issue by bmork** [beanz/anyevent-mqtt-perl#8]
_reconnect(), which is called on some errors, will unconditionally clear clean_session.  I assume this is done to force the broker to save and restore subscription state.  But this will not work on the first error if clean_session was set (default). 

And what's even worse:  This causes unwanted persistent sessions on the broker.  Rather unexpected, to me at least.

I believe the configured clean_session should be respected on reconnects as well. Subscription state should instead be restored on reconnect if clean_session is set.

I'll see if I can cook up something if you agree.

**Comment by beanz** [comment]
Fix merged and released. Thanks.
